### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/GeoPressureManual#1]
- [x] leaflet zoom button
- [x] references
- [x] try spell check correction
- [x] Youtube video in 16:9 ratio. 
- [x] Clearn list of reference at the end
- [x] plotly full width
